Taint configuration feature support
UnitTestBot/java-compilation-database pull request #195
Opened 2023-10-30 15:18 UTC by CaelmBleidd

2023-11-01 08:48 UTC, lehvolk requested changes

2023-11-01 08:48 UTC, lehvolk commented on settings.gradle.kts
> +include("jacodb-taint-configuration")
Do you want to be this package published to maven central?

2023-11-01 08:48 UTC, lehvolk commented on jacodb-taint-configuration/src/test/kotlin/org/jacodb/configuration/ConfigurationTest.kt
> +    @Disabled("We must have a special file with configs for tests")
Let's write at least some tests.

2023-11-07 08:18 UTC, lehvolk approved these changes

2023-11-07 08:19 UTC, merged

2023-11-07 08:50 UTC, Saloed commented on jacodb-taint-configuration/src/main/kotlin/org/jacodb/configuration/TaintConfigurationFeature.kt
> +            alternatives.forEach { classMatcher ->
It is better to use `findTypeOrNull` for resolved alternatives if possible, since `findSubClasses` will load all classes.

2023-11-07 08:51 UTC, Saloed commented on jacodb-taint-configuration/src/main/kotlin/org/jacodb/configuration/TaintConfigurationFeature.kt
> +        val functionName = if (method.isConstructor) "init^" else method.name
Maybe fix in json?

2023-11-07 08:54 UTC, Saloed commented on jacodb-taint-configuration/src/main/kotlin/org/jacodb/configuration/Util.kt
> +                if (char.isLetterOrDigit() || char == '.' || char == '\\' || char == '$' || char == '_') continue
Maybe we need some explanation for this set of symbols?