Comments adding
UnitTestBot/java-compilation-database pull request #67
Opened 2023-04-11 10:51 UTC by Nypiaka

comments adding

2023-04-19 01:56 UTC, Domonion requested changes

2023-04-19 01:56 UTC, Domonion commented on jacodb-analysis/src/main/kotlin/org/jacodb/analysis/codegen/CodeRepresentation.kt
> +                (dispatchValue.value as DirectStringSubstitution).substitution
no no no, do not do such casts, this is very very bad

2023-04-19 01:56 UTC, Domonion commented on jacodb-analysis/src/main/kotlin/org/jacodb/analysis/codegen/CodeRepresentation.kt
> +        }.toList().flatten()
flatMap

2023-04-19 01:56 UTC, Domonion commented on jacodb-analysis/src/main/kotlin/org/jacodb/analysis/codegen/CodeRepresentation.kt
> +        val numOfBreakingVarClass = numsOfDispatches[numsOfDispatches.size - 2].toInt()
Что такое -2?

2023-04-19 01:56 UTC, Domonion commented on jacodb-analysis/src/main/kotlin/org/jacodb/analysis/codegen/CodeRepresentation.kt
> +                "${(breakingVar as SimpleValueReference).shortName}.")
no casts

2023-04-19 01:56 UTC, Domonion commented on jacodb-analysis/src/main/kotlin/org/jacodb/analysis/codegen/CodeRepresentation.kt
> +                numsOfDispatches.size / readableConst + if (numsOfDispatches.size % readableConst == 0) 0 else 1
что это за логика

2023-04-19 01:56 UTC, Domonion commented on jacodb-analysis/src/main/kotlin/org/jacodb/analysis/codegen/CodeRepresentation.kt
> +            val currentComment: StringBuilder = StringBuilder()
зачеm 2 раза типизировать?

2023-04-19 01:56 UTC, Domonion commented on jacodb-analysis/src/main/kotlin/org/jacodb/analysis/codegen/CodeRepresentation.kt
> +            for (i in iterator * readableConst until minOf((iterator + 1) * readableConst, numsOfDispatches.size)) {
промежуточные вычисления вынести и проиmеновать

2023-04-19 01:56 UTC, Domonion commented on jacodb-analysis/src/main/kotlin/org/jacodb/analysis/codegen/CodeRepresentation.kt
> +        comments[numOfDispatchComments] = lastComment.substring(0, lastComment.length - 4)
откуда -4

2023-04-19 15:13 UTC, Nypiaka commented on jacodb-analysis/src/main/kotlin/org/jacodb/analysis/codegen/CodeRepresentation.kt
> +        comments[numOfDispatchComments] = lastComment.substring(0, lastComment.length - 4)
```[...," ", "-", ">"]```. I remove the unnecessary arrow and the space to it

2023-04-28 10:10 UTC, Domonion approved these changes

2023-05-02 12:46 UTC, merged